services:
  api:
    ....
  admin:
    ...
  shm-client:
    image: "danuk/shm-client-2:latest"
    pull_policy: always
    restart: always
    environment:
      - SHM_URL=http://api
      - APP_NAME="SHM Client"
     # - SHM_BASE_PATH=/
     # - TELEGRAM_BOT_NAME=my_telegram_bot
     # - TELEGRAM_BOT_AUTH_ENABLE=false
     # - SUPPORT_LINK=https://t.me/my_support

     # - TELEGRAM_WEBAPP_AUTH_ENABLE=false
     # - TELEGRAM_WEBAPP_AUTO_AUTH_ENABLE=false
     # - TELEGRAM_WEBAPP_PROFILE=telegram_bot
     # - OTP_ENABLE=true
     # - PASSKEY_ENABLE=true
    depends_on:
      - api
